### ISSUE TITLE
LocationScreen UI is cut off

### ISSUE THREAD

**Issue by mxnyee** [CodetheChangeFoundation/UHN-Mobile-App#111]
Seems to be on iOS only.
- Registered Location text field should not be hidden behind the Search button
- The "g" in "Registered Location" should not be cut off at the bottom
- Make all the text aligned to the left?
![87422320_935277083541818_5376414604861636608_n.jpg](https://images.zenhubusercontent.com/5d8534e2db42c800012543f2/2269cd89-3004-47c8-99a6-4cd09c0a4b96)

**Comment by Asiapenguin** [comment]
I have seen thsi happen on shorter Android devices as well
