### ISSUE TITLE
Onboarding & Getting Familiar

### ISSUE THREAD

**Issue by Asiapenguin** [CodetheChangeFoundation/UHN-Mobile-App#41]
- Clone the UHN-Mobile-App to see if there are missing information for setup instructions.
  - Mainly we use React Native with Expo for both iOS and Android development
  - The login/signup procedure will be replaced at a later date but is now linked to the backend server locally (UHN-Backend-Server repo)
- Should be able to launch the app, and with Backend-Server running, sign up a new user and login with that user. Some pages are done in terms of layout (with fake data) while others are just stubs.

**Comment by andrchoi** [comment]
Where are the setup instructions? I can't seem to find them.

**Comment by Asiapenguin** [comment]
Oh my! There are none I just realized... look into installing expo-cli and running expo start to get the repo running locally. Ofc all the npm install stuff beforehand. If you can make a PR for setup instructions locally as a project readme it will be swell 🔥
