### ISSUE TITLE
[UHN-MA-25] Remove Responders Page Layout

### ISSUE THREAD

**Issue by Asiapenguin** [CodetheChangeFoundation/UHN-Mobile-App#43]
[Figma](https://www.figma.com/file/kWGMq6ZU44PoqYXkUeEc5t/UHN?node-id=51%3A4)
- Follow v2 and create Remove Responders Page
- Use all the reusable components we have
- If theres any confusion on how the pages on Figma work with one another, ask @mxnyee

**Comment by mxnyee** [comment]
The UHN-MA-25 branch was forked off of the UHN-MA-26 branch, so merge the latter first
